# Generated by Django 2.1.7 on 2019-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190608_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Screenshot_156.png', upload_to='static/'),
        ),
    ]
