# Generated by Django 2.1.7 on 2019-05-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190516_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
    ]
