# Generated by Django 2.1.7 on 2019-06-09 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Catagory'),
            preserve_default=False,
        ),
    ]
