# Generated by Django 2.1.7 on 2019-06-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20190610_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
