# Generated by Django 2.1.7 on 2019-06-22 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20190621_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commented_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
