# Generated by Django 2.1.7 on 2019-06-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='repliedby',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
