# Generated by Django 2.2.12 on 2020-04-09 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0036_auto_20200403_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='viwes',
            field=models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
