# Generated by Django 2.2.12 on 2020-04-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_product_viwes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='viwes',
            new_name='views',
        ),
    ]
