# Generated by Django 2.2.12 on 2020-04-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_lat',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pro_lng',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
