# Generated by Django 2.2.12 on 2020-04-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20200413_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_lat',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='pro_lng',
            field=models.FloatField(blank=True, max_length=300, null=True),
        ),
    ]
