# Generated by Django 2.2.12 on 2020-04-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20200413_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bought_date',
            field=models.DateField(null=True),
        ),
    ]
