# Generated by Django 2.2.12 on 2020-04-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_auto_20200415_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
