# Generated by Django 2.2.12 on 2020-04-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_auto_20200415_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bought_date',
        ),
    ]
