# Generated by Django 2.2.12 on 2020-04-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_remove_product_bought_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bought_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
