# Generated by Django 2.2.12 on 2020-04-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0049_auto_20200416_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_catagory', models.CharField(max_length=100)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Catagory')),
            ],
        ),
    ]
