# Generated by Django 2.2.12 on 2020-04-18 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_subcatagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.SubCatagory'),
        ),
    ]
